### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by lorypelli** [TuringAI-Team/chatgpt-discord-bot#20]
Add button to regenerate response and make cooldown thing in chat command ephemeral

**Comment by iosonoagenda** [comment]
OkEttore ***@***.***+41 78 708 04 68
-------- Messaggio originale --------Da: RVG|lory ***@***.***> Data: 18.03.23  17:19  (GMT+01:00) A: MrlolDev/chatgpt-discord-bot ***@***.***> Cc: Subscribed ***@***.***> Oggetto: [MrlolDev/chatgpt-discord-bot] Suggestion (Issue #20) 
Add button to regenerate response and make cooldown thing in chat command ephemeral

**Comment by latuh** [comment]
Closing the issue due to inactivity and the bot being rewritten.
