### ISSUE TITLE
Issue with Supabase

### ISSUE THREAD

**Issue by ravisoni6262** [TuringAI-Team/chatgpt-discord-bot#55]
- I tried Supabase-js 2.21.0 and the version that ships with your code.

`npm ERR! code 1
npm ERR! path /root/chatgpt-discord-bot/node_modules/supabase
npm ERR! command failed
npm ERR! command sh -c node scripts/postinstall.js
npm ERR! file:///root/chatgpt-discord-bot/node_modules/supabase/scripts/postinstall.js:77
npm ERR!   ).original?.includes("global");
npm ERR!              ^
npm ERR! 
npm ERR! SyntaxError: Unexpected token '.'
npm ERR!     at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
npm ERR!     at async link (internal/modules/esm/module_job.js:42:21)

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-05-07T08_31_03_322Z-debug-0.log`

**Comment by f1nniboy** [comment]
Which Node version are you using?

**Comment by ravisoni6262** [comment]
> Which Node version are you using?
Thanks for pointing me in the right direction, I thought we new version of Linux, latest nodejs should be bundled.

**Comment by latuh** [comment]
Closing the issue due to inactivity and the bot being rewritten.
