### ISSUE TITLE
Failed to set up the cache manager

### ISSUE THREAD

**Issue by Jaymzu** [TuringAI-Team/chatgpt-discord-bot#63]
Hey there, 
I can't seem to get it running. It's looking for an URL and I don't know where it wants me to define it. Any suggestions?

npm run start

> start
> npm run build && npm run run

> build
> tsc

> run
> node --no-warnings build/main.js

error 09:01 AM » Failed to set up the cache manager -> Cannot read properties of undefined (reading 'url')

**Comment by f1nniboy** [comment]
This is an issue with the example config, I'll update it today.
For the mean time, change the `db` property to:
```json
    "db": {
        "supabase": {
            "url": "Supabase URL",
            "key": {
                "service": "SupaBase service API key"
            },
            "collections": {
                "users": "users",
                "conversations": "conversations",
                "guilds": "guilds",
                "interactions": "interactions",
                "images": "images",
                "keys": "keys"
            }
        },
        "redis": {
            "url": "Redis URL",
            "password": "Redis password",
            "port": 12345
        }
    }
    ```

**Comment by Jaymzu** [comment]
Thanks. That fixed the url problem.

**Comment by latuh** [comment]
Closing the issue as it has been resolved.
