### ISSUE TITLE
 "relation "public.users" does not exist"

### ISSUE THREAD

**Issue by Jaymzu** [TuringAI-Team/chatgpt-discord-bot#65]
Hey there, 
Managed to get the bot up and running. Started with dev info logged. Steps 1 -> 9 passed. However, when trying to interact with the bot on Discord. it spits the error below

An error occurred ⚠️
Failed to process interaction

Failed to perform database operation on collection 'users' with error message "relation "public.users" does not exist"

Terminal where the bot is started says the following. Note that 6156xxxxxx25917513 is specified in the config file as owner (and, ofc, it's my discord ID)
debug 06:08 AM » It took 9.74s for 1 cluster to be initialized.
info 06:08 AM » Up n' running!
#1 » debug 06:08 AM » get in cache collection users for key 6156xxxxxx25917513
#1 » debug 06:11 AM » get in cache collection users for key 6156xxxxxxx25917513
#1 » debug 06:11 AM » get in cache collection users for key 6156xxxxxxx25917513
#1 » debug 06:11 AM » get in cache collection users for key 6156xxxxxx25917513

**Comment by Jaymzu** [comment]
Looking in supabase it seems the database is not created/initialised. I see The bot's requests to (e..g) users and supabase returing 404

**Comment by f1nniboy** [comment]
You will have to create all of the required Supabase databases manually, there will be better docs on how to set them up soon

**Comment by f1nniboy** [comment]
Did you also create them with all the needed rows?

**Comment by Jaymzu** [comment]
Seems so. No more "can't find stuff" errors ;) I'll open new issues for the other stuff (I assume you'd rather have stuff reported like this rather than in one big thread)

**Comment by latuh** [comment]
Closing the issue due to inactivity and the bot being rewritten.
