### ISSUE TITLE
The model: gpt-4 does not exist

### ISSUE THREAD

**Issue by Jaymzu** [TuringAI-Team/chatgpt-discord-bot#66]
Hey there, 
I managed to get ChatGPT working just fine. Fixed tables, sub tables & permissions. Now I'm starting to test modules ;)
I selected GPT-4 and tried asking the bot a question. Debug log spitted out the error below. Any idea?

  options: {
    type: 'API',
    data: {
      endpoint: '/chat/completions',
      code: 404,
      id: 'invalid_request_error',
      message: 'The model: `gpt-4` does not exist'

**Comment by Jaymzu** [comment]
Apparently GPT-4 is not supported by the openai API just yet (at a quick glance)

**Comment by Delamcode** [comment]
This is just because your account doesn’t support GPT-4 yet. It is waitlist only at the moment.

**Comment by latuh** [comment]
Closing the issue due to inactivity and the bot being rewritten.
