### ISSUE TITLE
trying to save text id to integer field in images

### ISSUE THREAD

**Issue by Jaymzu** [TuringAI-Team/chatgpt-discord-bot#68]
Hey there, 

While doing /imagine ai It seems the bot is trying to save an image id of an alphanumeric format (e.g. c2c6fb28-432e-415d-a33c-ed95fb0a85fc) into the id field of the supabase collection images. Problem is that the id field comes predefined as integer and, as such, doesn't support regular text. I tried moving the original id to id2 and providing a text id field, it stopped complaining about the format but other stuff started breaking so I rolled back. 

#1 » error 09:37 AM » Something went wrong while trying to save e6d47935-9dc1-4a8e-9b80-4cc3dbd913e4 to collection images -> {
  code: '22P02',
  details: null,
  hint: null,
  message: 'invalid input syntax for type smallint: "e6d47935-9dc1-4a8e-9b80-4cc3dbd913e4"'
}

**Comment by latuh** [comment]
Closing the issue due to inactivity and the bot being rewritten.
