### ISSUE TITLE
RabbitMQ error handling

### ISSUE THREAD

**Issue by cody-greene** [TuringAI-Team/chatgpt-discord-bot#77]
**Problem:**
The [RabbitMQ connection](https://github.com/TuringAI-Team/chatgpt-discord-bot/blob/05faf328babfcf70c1ac6330653c591177c357cf/src/turing/connection/connection.ts#L43) and [Consumer](https://github.com/TuringAI-Team/chatgpt-discord-bot/blob/05faf328babfcf70c1ac6330653c591177c357cf/src/turing/connection/connection.ts#L51) are both event emitters which can emit "error" events. If these events are not handled, then they bubble up to the top of the event loop and crash the application.

Example situations which will emit an error:
- restarting the rabbit server
- deleting / re-creating the consumer queue
- temporary network connectivity loss

**Solution:**
```javascript
client.on("error", err => console.log("rabbitmq connection error", err))
consumer.on("error", err => console.log(`rabbitmq consumer (${queueName}) error`, err))
```
Or the equivalent with whatever logging mechanism you have.

**Comment by latuh** [comment]
I'm closing this issue as we are rewriting the bot,and this has been implemented, thank you!
