### ISSUE TITLE
When send the message ask to get Premium

### ISSUE THREAD

**Issue by rafagaseo** [TuringAI-Team/chatgpt-discord-bot#8]
When message is written on Discord, this message comes: 

Use this command again 3h>.
If you want to avoid this cooldown you can donate to get premium. If you want to donate use the command /premium buy .

**Comment by MrlolDev** [comment]
Thanks for the report checking it

**Comment by latuh** [comment]
Closing the issue due to inactivity and the bot being rewritten.
